name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - os: linux
            arch: "amd64"
          - os: linux
            arch: "arm64"
          - os: darwin
            arch: "amd64"
          - os: darwin
            arch: "arm64"
          - os: windows
            arch: "amd64"

    name: Build and publish package
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: actions/setup-go@v1
        with:
          go-version: "~1.17.5"

      - run: echo "EXTENSION=.exe" >> $GITHUB_ENV
        if: matrix.target.os == 'windows'

      - run: echo "FILENAME=sshs-${{ github.event.release.tag_name }}-${{ matrix.target.os }}-${{ matrix.target.arch }}${{ env.EXTENSION }}" >> $GITHUB_ENV

      - run: go build -o bin/${{ env.FILENAME }} .
        env:
          GOOS: "${{ matrix.target.os }}"
          GOARCH: "${{ matrix.target.arch }}"

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ env.FILENAME }}
          tag: ${{ github.ref }}
